#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhoneToolClickable

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PhoneToolClickable.BP_PhoneToolClickable_C
// 0x0040 (0x05F0 - 0x05B0)
class ABP_PhoneToolClickable_C : public ASBZPhoneTool
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         ControlID;                                         // 0x05B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5BC[0x4];                                      // 0x05BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZControlsReference                  In_Controls_Reference_Idle;                        // 0x05C0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_BP_PhoneToolClickable(int32 EntryPoint);
	void OnActivated();
	void OnCanceled();
	void OnReady();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PhoneToolClickable_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PhoneToolClickable_C")
	}
	static class ABP_PhoneToolClickable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhoneToolClickable_C>();
	}
};

SDK_NAMESPACE_END
